runtime: java11
entrypoint: 'java -javaagent:sqreen.jar -jar springboot-helloworld-j11-0.0.1-SNAPSHOT.jar' 

health_check:
  enable_health_check: False

env_variables:
  SQREEN_APP_NAME: XXXXXXXXX
  SQREEN_TOKEN: env_org_XXXXXXXXX
